# Generated by Django 5.2.10 on 2026-02-02 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('partner', 'Партнер'), ('store', 'Магазин/Продавец')], default='partner', max_length=10, verbose_name='Тип пользователя'),
        ),
    ]
